export const createTrekMap = ({ api, trekId, urlLayer, center, zoom, attribution, colorTrekLine, colorDepartureIcon, colorArrivalIcon, colorSensitiveArea, colorPoiIcon }) => {
  const container = document.createElement('div');
  container.style = 'height: 100%';
  const trek = document.createElement('grw-trek-provider');
  trek.setAttribute('api', api);
  trek.setAttribute('trek-id', trekId);
  container.appendChild(trek);
  const trekMap = document.createElement('grw-map');
  trekMap.setAttribute('url-layer', urlLayer);
  trekMap.setAttribute('center', center);
  trekMap.setAttribute('zoom', zoom);
  trekMap.setAttribute('attribution', attribution);
  trekMap.setAttribute('color-trek-line', colorTrekLine);
  trekMap.setAttribute('color-departure-icon', colorDepartureIcon);
  trekMap.setAttribute('color-arrival-icon', colorArrivalIcon);
  trekMap.setAttribute('color-sensitive-area', colorSensitiveArea);
  trekMap.setAttribute('color-poi-icon', colorPoiIcon);
  container.appendChild(trekMap);
  return container;
};
