export const createTreksList = ({ api, language, inBbox, cities, districts, structures, themes, portals, routes, practices, colorPrimary, colorPrimaryTint }) => {
  const container = document.createElement('div');
  const treks = document.createElement('grw-treks-provider');
  treks.setAttribute('api', api);
  treks.setAttribute('language', language);
  inBbox && treks.setAttribute('in-bbox', inBbox);
  cities && treks.setAttribute('cities', cities);
  districts && treks.setAttribute('districts', districts);
  structures && treks.setAttribute('structures', structures);
  themes && treks.setAttribute('themes', themes);
  portals && treks.setAttribute('portals', portals);
  routes && treks.setAttribute('routes', routes);
  practices && treks.setAttribute('practices', practices);
  container.appendChild(treks);
  const list = document.createElement('grw-treks-list');
  list.setAttribute('color-primary', colorPrimary);
  list.setAttribute('color-primary-tint', colorPrimaryTint);
  container.appendChild(list);
  return container;
};
