name: 'Node modules - get or set in cache'
description: 'Get node_modules from cache else generate it'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Setup node
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        registry-url: https://registry.npmjs.org/

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: |
        npm ci

